### ISSUE TITLE
[Bug] Cannot upload video files

### ISSUE THREAD

**Issue by skjnldsv** [abramenal/cypress-file-upload#57]
Hello again :)

The images processing works fine!
Though I started creating the video tests I have and it failed directly.
After some digging, it might be that the fixture base64 doesn't work with videos.

How can I use your plugin with hex or binary?
Or do you have any other workaround? :)

Thanks a lot!

**Comment by skjnldsv** [comment]
``` js
TypeError: Cannot read property 'message' of undefined

Because this error occurred during a 'before all' hook we are skipping the remaining tests in the current suite: 'Open Videos in viewer'
    at new r (http://localhost:8000/__cypress/tests?p=cypress/support/index.js-457:453:539)
    at http://localhost:8000/__cypress/tests?p=cypress/support/index.js-457:453:1761
    at http://localhost:8000/__cypress/tests?p=cypress/support/index.js-457:453:1787
    at Array.map (<anonymous>)
    at Context.<anonymous> (http://localhost:8000/__cypress/tests?p=cypress/support/index.js-457:453:1394)
From previous event:
    at getRet (http://localhost:8000/__cypress/runner/cypress_runner.js:54380:16)
From previous event:
    at Context.thenFn (http://localhost:8000/__cypress/runner/cypress_runner.js:54394:26)
    at Context.then (http://localhost:8000/__cypress/runner/cypress_runner.js:54654:21)
    at Context.<anonymous> (http://localhost:8000/__cypress/runner/cypress_runner.js:61586:21)
    at http://localhost:8000/__cypress/runner/cypress_runner.js:61291:33
From previous event:
    at runCommand (http://localhost:8000/__cypress/runner/cypress_runner.js:61281:14)
    at next (http://localhost:8000/__cypress/runner/cypress_runner.js:61365:14)
    at http://localhost:8000/__cypress/runner/cypress_runner.js:61377:18
From previous event:
    at next (http://localhost:8000/__cypress/runner/cypress_runner.js:61365:34)
From previous event:
    at http://localhost:8000/__cypress/runner/cypress_runner.js:61384:37
From previous event:
    at run (http://localhost:8000/__cypress/runner/cypress_runner.js:61382:15)
    at Object.cy.(anonymous function) [as nextcloudCreateUser] (http://localhost:8000/__cypress/runner/cypress_runner.js:61610:11)
    at Context.runnable.fn (http://localhost:8000/__cypress/runner/cypress_runner.js:61740:20)
    at callFn (http://localhost:8000/__cypress/runner/cypress_runner.js:30560:21)
    at Hook.Runnable.run (http://localhost:8000/__cypress/runner/cypress_runner.js:30553:7)
    at http://localhost:8000/__cypress/runner/cypress_runner.js:64685:28
From previous event:
    at Object.onRunnableRun (http://localhost:8000/__cypress/runner/cypress_runner.js:64680:20)
    at $Cypress.action (http://localhost:8000/__cypress/runner/cypress_runner.js:60037:51)
    at Hook.Runnable.run (http://localhost:8000/__cypress/runner/cypress_runner.js:63746:20)
    at next (http://localhost:8000/__cypress/runner/cypress_runner.js:30899:10)
    at http://localhost:8000/__cypress/runner/cypress_runner.js:30921:5
    at timeslice (http://localhost:8000/__cypress/runner/cypress_runner.js:26162:27)
```

**Comment by abramenal** [comment]
@skjnldsv 
thanks for submitting the issue (again)! 😄 

Have you tried setting `encoding` explicitly?
https://github.com/abramenal/cypress-file-upload#api

**Comment by skjnldsv** [comment]
Aaaand i'll stop bothering you now I think! :see_no_evil: 
I actually did try that before. I tried combining base64, hex, binary, but it was always failing. I did a lot of code change since and now specifying the encoding to binary seems to work.

No idea what was the issue before then, but it's working great now!
Thanks again! :wink:

**Comment by skjnldsv** [comment]
Aaha, this time I have something :)
Okay, the file indeed gets uploaded, but it gets corrupted.

proper one: 
`feb1d00f4c31952519e206ec9c927a63  video1.mp4`
File on the test server
`24fba509f698e024d1ff9e0415bb4414  video1.mp4`

Any help?

**Comment by skjnldsv** [comment]
This is a :roller_coaster: :grin: 
Okay, so after trying to combine different options, 'base64' in the fixture AND in you file-upload plugin works fine for both :tada: 

Thanks a lot for your help @abramenal :hugs: :bowing_woman:

**Comment by adventmedia** [comment]
I cannot upload a video file with the current version (3.4.0)
![e2e-test 2019-11-04 09-37-37](https://user-images.githubusercontent.com/1529172/68128979-bee32080-fee6-11e9-99e2-330744b19cdd.jpg)

The code: 
```    cy.fixture('images/sample_video.mp4', 'base64').then(fileContent => {
      cy.get('input.uppy-Dashboard-input').upload(
        { fileContent, fileName: 'sample_video.mp4', mimeType: 'video/mp4' },
        { subjectType: 'input' }
      );
    });
```
Also tried with 'binary' for encoding, same error.
